# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: true
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # sf dependencies:
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # postgis/liblwgeom source compile dependencies:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  - sudo ldconfig
